#pragma once

namespace CStell
{
	using MouseCode = uint16_t;

	namespace Mouse
	{
		enum : MouseCode
		{
			// From glfw3.h
			CSTELL_BUTTON0 = 0,
			CSTELL_BUTTON1 = 1,
			CSTELL_BUTTON2 = 2,
			CSTELL_BUTTON3 = 3,
			CSTELL_BUTTON4 = 4,
			CSTELL_BUTTON5 = 5,
			CSTELL_BUTTON6 = 6,
			CSTELL_BUTTON7 = 7,

			CSTELL_BUTTON_LAST = CSTELL_BUTTON7,
			CSTELL_BUTTON_LEFT = CSTELL_BUTTON0,
			CSTELL_BUTTON_RIGHT = CSTELL_BUTTON1,
			CSTELL_BUTTON_MIDDLE = CSTELL_BUTTON2
		};
	}
}