#pragma once

// From glfw3.h
#define CSTELL_MOUSE_BUTTON_1         0
#define CSTELL_MOUSE_BUTTON_2         1
#define CSTELL_MOUSE_BUTTON_3         2
#define CSTELL_MOUSE_BUTTON_4         3
#define CSTELL_MOUSE_BUTTON_5         4
#define CSTELL_MOUSE_BUTTON_6         5
#define CSTELL_MOUSE_BUTTON_7         6
#define CSTELL_MOUSE_BUTTON_8         7
#define CSTELL_MOUSE_BUTTON_LAST      CSTELL_MOUSE_BUTTON_8
#define CSTELL_MOUSE_BUTTON_LEFT      CSTELL_MOUSE_BUTTON_1
#define CSTELL_MOUSE_BUTTON_RIGHT     CSTELL_MOUSE_BUTTON_2
#define CSTELL_MOUSE_BUTTON_MIDDLE    CSTELL_MOUSE_BUTTON_3